/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.User;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("Application Started");
        Scanner input = new Scanner(System.in);

        System.out.println("Choose options");
        System.out.println("1: Sign Up");
        System.out.println("2: Login");
        System.out.println("3: Fetch Bookings");
        System.out.println("4: Search Trains");
        System.out.println("5: Book Seats");
        System.out.println("6: Cancel My Booking");
        System.out.println("7: Exit the app");
        int i = input.nextInt();


        switch (i){
            case 1:
                System.out.println("Sign Up");
                System.out.println("Enter Username");
                String usernameToSignup = input.next();
                System.out.println("Enter Password");
                String passwordToSignUp = input.next();
                System.out.println("username: " + usernameToSignup + " " + "password: " + passwordToSignUp);
                User user1 = new User(usernameToSignup,passwordToSignUp);
                System.out.println("User Created: " + user1.getUsername() + " | " + user1.getPassword());
                break;

            case 2:
                System.out.println("Login");;
                System.out.println("Enter Username");
                String usernameToLogin = input.next();
                System.out.println("Enter Password");
                String passwordToLogin = input.next();
                System.out.println("username: " + usernameToLogin + " " + "password: " + passwordToLogin);
                break;

            case 3:
                System.out.println("Fetch Bookings");
                System.out.println("Enter Username");
                String username = input.next();
                break;

            case 4:
                System.out.println("Search Trains");
                System.out.println("Enter Source");
                String source = input.next();
                System.out.println("Enter Destination");
                String destination = input.next();
                break;

            case 5:
                System.out.println("Book Seats");
                break;

            case 6:
                System.out.println("Cancel My Booking");
                break;

            case 7:
                System.out.println("Exit the app");
                break;

            default:
                System.out.println("default");
        }
    }
}
